services:

  device-registry:
    build: .
    ports:
      - '8085:8085'
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge