name: Docker Image CI - Build

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag device-registry:$(date +%s)