name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  publish_image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ousan/device-registry:$(date +%s)
    - name: Push image to Docker Hub
      run: |
        docker login -u ousan
        docker push ousan/device-registry:$(date +%s)
